name: ParamaLegends
version: 1.0.0
author: cuna
main: me.cuna.paramalegends.ParamaLegends
api-version: 1.18
commands:
  yourmom:
    description: Doing your mom, doing doing your mom.
    usage: /yourmom <user>
  startgame:
    description: Start Parama Legends. Make sure game is setup by using /setupgame
    usage: /startgame <areasize>
    permission: paramalegends.gameadmin
    permission-message: You are not a game admin!
  setupgame:
    description: Begin Parama Legends game setup.
    usage: /setupgame
    permission: paramalegends.gameadmin
    permission-message: You are not a game admin!
  lectrum:
    description: Check or pay lectrum.
    usage: /lectrum [balance|pay]
  destiny:
    description: Check your destiny.
  spawnaltar:
    description: Spawn a custom ParamaLegends altar or NPC.
    usage: /spawnaltar <altarname>
    permission: paramalegends.gameadmin
    permission-message: You are not a game admin!
  removealtar:
    description: Remove a nearby ParamaLegends altar or NPC.
    usage: /removealtar
    permission: paramalegends.gameadmin
    permission-message: You are not a game admin!
  destinyset:
    description: Set the destiny of a player.
    usage: /destinyset <player> <destiny> <level>
    permission: paramalegends.gameadmin
    permission-message: You are not a game admin!
  lectrumset:
    description: Set the lectrum of a player.
    usage: /lectrumset <player> <lectrum>
    permission: paramalegends.gameadmin
    permission-message: You are not a game admin!
  worldlevelset:
    description: Set the world level.
    usage: /worldlevelset <level>
    permission: paramalegends.gameadmin
    permission-message: You are not a game admin!
  whatsnew:
    description: Check out what's new in the ParamaLegends plugin.
    usage: /whatsnew
  bloodmoon:
    description: Start or stop a blood moon event.
    usage: /bloodmoon <start/stop>
    permission: paramalegends.gameadmin
    permission-message: You are not a game admin!
  dragonfightstop:
    description: Stop dragon fight (counts as loss)
    usage: /dragonfightstop
    permission: paramalegends.gameadmin
    permission-message: You are not a game admin!
  setmayor:
    description: Set the mayor of the server
    usage: /setmayor <player>
    permission: paramalegends.gameadmin
    permission-message: You are not a game admin!
  safezone:
    description: Minimize or maximize safe zone size
    usage: /safezone <maximize/minimize>
    permission: paramalegends.gameadmin
    permission-message: You are not a game admin!
  leaderboard:
    description: View the server's top players
    usage: /leaderboard
  tip:
    description: Tip another player
    usage: /tip <player>
  party:
    description: Manage your party
    usage: /party <create/invite/leave/kick/info/accept>
  coords:
    description: Broadcast your coordinates
    usage: /coords
  votekick:
    description: Vote to kick a player
    usage: /votekick <player>
  practice:
    description: Toggle practice mode
    usage: /practice
  bal:
    description: Check lectrum
    usage: /bal
  balance:
    description: Check lectrum
    usage: /balance
  pay:
    description: Pay lectrum
    usage: /pay [player] [amount]
permissions:
  paramalegends.gameadmin:
    description: Allows you to start and modify the current Parama Legends game.
    default: op
depend: [WorldGuard]