mobs:
  zombie:
    health: 50
    damage: 10
    lectrum: 3
    exp: 25
  spider:
    damage: 6
    health: 30
    lectrum: 3
    exp: 25
  skeleton:
    health: 30
    arrowbonusdamage: 5
    lectrum: 2
    exp: 20
  creeper:
    health: 40
    explosionradius: 6
    maxfuseticks: 10
    lectrum: 5
    exp: 30
  witch:
    health: 40
    lectrum: 2
    exp: 25
players:
destinylevelunlock:
  magic:
    1: Fling Earth
    1t: Active
    2: Ignite
    2t: Active
    3: Gust
    3t: Active
    4: Life Drain
    4t: Active
    5: Blink
    5t: Active
    6: Summon Lightning
    6t: Active
    7: Illusory Orb
    7t: Active
    8: Dragon's Breath
    8t: Active
    9: Voices of the Damned
    9t: Active
    10: Nova
    10t: Active
  swordsmanship:
    1: Precise Blade
    1t: Passive
    2: Crippling Blow
    2t: Passive
    3: Shields Up
    3t: Active
    4: Reaver
    4t: Passive
    5: Phoenix Dive
    5t: Active
    6: Enrage
    6t: Active
    7: Onslaught
    7t: Active
    8: Terrifying Cruelty
    8t: Active
    9: Superconducted
    9t: Active
    10: Calamity
    10t: Active
  reaper:
    1: Coated Blade
    1t: Passive
    2: Hidden Strike
    2t: Active
    3: Blinding Sand
    3t: Active
    4: Why are you hitting yourself?
    4t: Passive
    5: Too slow!
    5t: Passive
    6: Second Wind
    6t: Passive
    7: Bloody Fervour
    7t: Passive
    8: Gut Punch
    8t: Active
    9: Forbidden Slash
    9t: Active
    10: Memento Mori
    10t: Passive
passivedescriptions:
  swordsmanship:
    1: Increased crit damage and crit rate.
    2: Each fifth attack cripples         enemies.
    4: Increased cleave damage,  crit damage and crit rate.
levelupmessage:
  magic:
    2: You begin to fathom the essence of fire.
    3: The wind whispers in your ear.
    4: You start to feel the life of lesser beings.
    5: The world appears to shrink before you.
    6: The secrets of thunder are revealed to you.
    7: You begin to study arcanery from other worlds.
    8: Even the power of mighty dragons serve you.
    9: You hear wails of pain from deep below.
    10: Your mastery of magic is now unparalleled.


