name: ParamaAnjingCraft
version: 1.0.0
author: cuna
main: id.cuna.ParamaAnjingCraft.ParamaAnjingCraft
api-version: 1.17
commands:
  yourmom:
    description: Doing your mom, doing doing your mom.
    usage: /yourmom <user>
  startgame:
    description: Start le epic game!.
    usage: Command can only be issued by player.
    permission: paramaanjingcraft.gameadmin
    permission-message: You are not a game admin!
permissions:
  paramaanjingcraft.gameadmin:
    description: Allows you to start and modify the current ParamaAnjingCraft game.
    default: op
depend: [WorldGuard]