name: ParamaLegends
version: 1.0.0
author: cuna
main: id.cuna.ParamaLegends.ParamaLegends
api-version: 1.17
commands:
  yourmom:
    description: Doing your mom, doing doing your mom.
    usage: /yourmom <user>
  startgame:
    description: Start Parama Legends. Make sure game is setup by using /setupgame
    usage: /startgame <areasize>
    permission: paramalegends.gameadmin
    permission-message: You are not a game admin!
  setupgame:
    description: Begin Parama Legends game setup.
    usage: /setupgame
    permission: paramalegends.gameadmin
    permission-message: You are not a game admin!
  lectrum:
    description: Check or pay lectrum.
    usage: /lectrum [balance|pay]
  destiny:
    description: Check your destiny.
  spawnaltar:
    description: Spawn a custom ParamaLegends altar or NPC.
    usage: /spawnaltar <altarname>
    permission: paramalegends.gameadmin
    permission-message: You are not a game admin!
  removealtar:
    description: Remove a nearby ParamaLegends altar or NPC.
    usage: /removealtar
    permission: paramalegends.gameadmin
    permission-message: You are not a game admin!
  destinyset:
    description: Set the destiny of a player.
    usage: /destinyset <player> <destiny> <level>
    permission: paramalegends.gameadmin
    permission-message: You are not a game admin!
  lectrumset:
    description: Set the lectrum of a player.
    usage: /lectrumset <player> <lectrum>
    permission: paramalegends.gameadmin
    permission-message: You are not a game admin!
  worldlevelset:
    description: Set the world level.
    usage: /worldlevelset <level>
    permission: paramalegends.gameadmin
    permission-message: You are not a game admin!
permissions:
  paramalegends.gameadmin:
    description: Allows you to start and modify the current Parama Legends game.
    default: op
depend: [WorldGuard]